Iteration_path_train_1: ./results/AL_Seq_2022-02-18_09-10-02/Iteration_train_1
Iteration_path_train_2: ./results/AL_Seq_2022-02-18_09-10-02/Iteration_train_2
Iteration_path_train_3: ./results/AL_Seq_2022-02-18_09-10-02/Iteration_train_3
batch_sz: 3000
init_batch_sz: 100
main_directory: ./results/AL_Seq_2022-02-18_09-10-02
n_chunk_test: 1
n_chunk_train: 2
n_chunks: 3
report_directory: ./results/AL_Seq_2022-02-18_09-10-02/report_2022-02-18_09-10-02.txt
results_AL_EnS_avg: ./results/AL_Seq_2022-02-18_09-10-02/Iteration_train_3/AL_EnS_avg/results_AL_EnS_avg.csv
results_AL_RF_US: ./results/AL_2022-03-01_13-43-41/Iteration_train_3/AL_RF_US/results_AL_RF_US.csv
results_AL_SVM_US: ./results/AL_2022-03-01_13-43-41/Iteration_train_3/AL_SVM_US/results_AL_SVM_US.csv
results_PL_RF: ./results/AL_Seq_2022-02-18_09-10-02/Iteration_train_3/PL_RF/results_PL_RF.csv
